name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the next release
        required: true

jobs:
  release:
    name: Create release/${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: magefiles/go.mod

      - name: Validate release version
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: "sync:validateRelease"
        env:
          BOTKUBE_RELEASE_VERSION: "${{ inputs.version }}.0"

      - name: install npm
        run: |
          npm install

      - name: Prettier check
        run: |
          npm run prettier:fix

      - name: Running misspell check
        uses: reviewdog/action-misspell@v1
        with: 
          # github_token:  ${{ secrets.GH_TOKEN }}
          pattern: "**.md"
          level: error
          locale: "US"
          exclude: |
            ./.git/*
            ./.cache/*

      - name: Run LanguageTool
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
          level: error
          patterns: "**/*.md **/*.txt"
          custom_api_endpoint: ''
          ### Flags for LanguageTool ###
          # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
          language: 'en-US'
          enabled_rules: ''
          disabled_rules: 'WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE,DOUBLE_PUNCTUATION'
          enabled_categories: ''
          disabled_categories: 'TYPOS,TYPOGRAPHY,CASING'
          enabled_only: 'false'




      
          