name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the next release
        required: true

jobs:
  release:
    name: Create release/${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: magefiles/go.mod

      - name: Validate release version
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: "sync:validateRelease"
        env:
          BOTKUBE_RELEASE_VERSION: "${{ inputs.version }}.0"

      - name: install npm
        run: |
          npm install

      - name: Prettier check
        run: |
          npm run prettier:fix
